BaseConfig:
  minDetectorConfidence: 0.4

TargetManagement:
  maxTargetsPerStream: 150
  probationAge: 20 # this use the video FPS(30), no the inference FPS
  maxShadowTrackingAge: 60
  earlyTerminationAge: 15

DataAssociator:
  associationMatcherType: 1   # IoU
  checkClassMatch: 1
  minMatchingScore4Iou: 0.35

StateEstimator:
  stateEstimatorType: 2       # Kalman
